# CK+_AC_CAE_test.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 'CK+_AC_CAE_test'
    EXPERIMENT_PATH: '../autodl-tmp/results/CK+_AC-CAE'
    SAVE_FREQ: 100
    PRINT_FREQ: 30
    
DATA:
    IMG_SIZE: 112
    BATCH_SIZE: 32
    DATASET: 'CK+'
    DATA_PATH: '../FERdatasets/CK+'
    

MODEL:
    ARCH: 'AC-CAE_single'
    DEPTH: 8
    DROP_PATH: 0.5
    
    MLP_LAYER: 'linear'
    TOKEN_SE: 'conv2d'
    
    
TRAIN:
    EPOCHS: 200
    BASE_LR: 1e-4
    
    OPTIMIZER:
        NAME: 'esamAdam'
        EPS: 1e-8
        BETAS: (0.9, 0.999)
        RHO: 0.05
        
    LR_SCHEDULER:
        NAME: 'exponential'
        GAMMA: 0.98
        
    CRITERION:
        NAME: 'POSTERCrossEntropy'
        
AUG:
    MIXUP: 0.
    
    