# FERPlus_CLSFERBaseline.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 'CLSFERBaseline_FERPlus_LR'
    EXPERIMENT_PATH: '../autodl-tmp/results/RAF-DB_CLSFERBaseline_FERPlus_LR'
    SAVE_FREQ: 30
    
DATA:
    BATCH_SIZE: 256
    DATASET: 'FERPlus'
    DATA_PATH: '../autodl-tmp/FERPlus'
    
MODEL:
    ARCH: 'CLSFERBaseline_stage3'
    DEPTH: 8
    
TRAIN:
    EPOCHS: 60
    BASE_LR: 5e-5
    
    OPTIMIZER:
        NAME: 'Adam'
        EPS: 1e-8
        BETAS: (0.9, 0.999)
        
    LR_SCHEDULER:
        NAME: 'None'
        
    CRITERION:
        NAME: 'CrossEntropy'
    
    