# FERPlus_200epoch_Reduce_Scheduler.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 'CLSFERBaseline_Reduce_Scheduler_FERPlus'
    EXPERIMENT_PATH: '../autodl-tmp/results/FERPlus_Reduce_Scheduler'
    SAVE_FREQ: 30
    
DATA:
    BATCH_SIZE: 256
    DATASET: 'FERPlus'
    DATA_PATH: '../autodl-tmp/FERPlus'
    IMG_SIZE: 112
    
MODEL:
    ARCH: 'CLSFERBaseline_stage3'
    DEPTH: 8
    
TRAIN:
    EPOCHS: 200
    BASE_LR: 1e-4
    MIN_LR: 1e-7
    
    OPTIMIZER:
        NAME: 'Adam'
        EPS: 1e-8
        BETAS: (0.9, 0.999)
        
    LR_SCHEDULER:
        NAME: 'reduce'
        REDUCE_FACTOR: 0.5
        
    CRITERION:
        NAME: 'CrossEntropy'
        
AUG:
    MIXUP: 0.
    
    