# JAFFE_AC-CAE-tSNE.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 't-SNE'
    EXPERIMENT_PATH: '../autodl-tmp/results/JAFFE_AC-CAE_tSNE'
    SAVE_FREQ: 100
    PRINT_FREQ: 30
    
DATA:
    BATCH_SIZE: 200
    DATASET: 'JAFFE'
    DATA_PATH: '../autodl-tmp/JAFFE'
    IMG_SIZE: 112
    
MODE:
    FINETUNE: True
    
MODEL:
    ARCH: 'AC-CAE_single'
    DEPTH: 8
    DROP_PATH: 0.5
    MLP_RATIO: 4.
    
    MLP_LAYER: 'linear'
    TOKEN_SE: 'linear'
    
TRAIN:
    EPOCHS: 200
    BASE_LR: 1e-4
    RESUME: 'autodl-tmp/results/RAF-DN_AC-CAE_[05-26]-[18-31]_89.830/checkpoint/best.pth'
    
    OPTIMIZER:
        NAME: 'samAdam'
        RHO: 0.1
        
    LR_SCHEDULER:
        NAME: 'exponential'
        
    CRITERION:
        NAME: 'POSTERCrossEntropy'
        LABEL_SMOOTHING: 0.1
        
AUG:
    MIXUP: 0.
    
    
    