# JAFFE_AC-CAE-tSNE.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 't-SNE'
    EXPERIMENT_PATH: '../autodl-tmp/results/JAFFE_AC-CAE_tSNE'
    SAVE_FREQ: 100
    PRINT_FREQ: 30
    
DATA:
    IMG_SIZE: 112
    BATCH_SIZE: 64
    DATASET: 'JAFFE'
    DATA_PATH: '../FERdatasets/JAFFE'
    
MODE:
    T_SNE: True
    
MODEL:
    ARCH: '14x14_CLSFER_addpatches'
    DEPTH: 8
    DROP_PATH: 0.5
    
    MLP_LAYER: 'linear'
    TOKEN_SE: 'conv2d'
    
    
TRAIN:
    EPOCHS: 200
    BASE_LR: 3.5e-5
    RESUME: 'D:\College\projects\autodl-tmp\results\JAFFE_AC-CAE_[05-26]-[01-27]_95.35\checkpoint\best.pth'
    
    OPTIMIZER:
        NAME: 'esamAdam'
        EPS: 1e-8
        BETAS: (0.9, 0.999)
        RHO: 0.05
        
    LR_SCHEDULER:
        NAME: 'exponential'
        GAMMA: 0.98
        
    CRITERION:
        NAME: 'POSTERCrossEntropy'
        
AUG:
    MIXUP: 0.
    
    