# RAF-DB_CLSFERBaseline.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 'CLSFERBaseline_depth2_WithOutDecay_200epoch'
    EXPERIMENT_PATH: '../autodl-tmp/results/RAF-DB_CLSFERBaseline_WithOutDecay_200epoch'
    SAVE_FREQ: 30
    
DATA:
    BATCH_SIZE: 256
    DATASET: 'RAF-DB'
    DATA_PATH: '../autodl-tmp/RAF-DB'
    
MODEL:
    ARCH: 'CLSFERBaseline'
    DEPTH: 2
    
TRAIN:
    EPOCHS: 200
    BASE_LR: 4e-4
    
    OPTIMIZER:
        NAME: 'Adam'
        EPS: 1e-7
        BETAS: (0.9, 0.999)
        
    LR_SCHEDULER:
        NAME: 'None'
        
    CRITERION:
        NAME: 'CrossEntropy'
    
    