# RAF-DB_14x14.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 'RAF-DB_14x14'
    EXPERIMENT_PATH: '../autodl-tmp/results/RAF-DB_14x14'
    SAVE_FREQ: 100
    
DATA:
    BATCH_SIZE: 256
    DATASET: 'RAF-DB'
    DATA_PATH: '../autodl-tmp/RAF-DB'
    IMG_SIZE: 112
    
MODEL:
    ARCH: 'NonMultiCLSFER_addpatches'
    DEPTH: 8
    DROP_PATH: 0.5
    MLP_RATIO: 4.
    
TRAIN:
    EPOCHS: 200
    BASE_LR: 1e-4
    
    OPTIMIZER:
        NAME: 'samAdam'
        EPS: 1e-8
        BETAS: (0.9, 0.999)
        
    LR_SCHEDULER:
        NAME: 'exponential'
        
    CRITERION:
        NAME: 'POSTERCrossEntropy'
        LABEL_SMOOTHING: 0.1
        
AUG:
    MIXUP: 0.
    
    