# RAF-DB_CLSFERBaseline.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 'CLSFERBaseline_depth2_SearchLR'
    EXPERIMENT_PATH: '../autodl-tmp/results/RAF-DB_CLSFERBaseline_depth2_SearchLR'
    SAVE_FREQ: 30
    
DATA:
    BATCH_SIZE: 256
    DATASET: 'RAF-DB'
    DATA_PATH: '../autodl-tmp/RAF-DB'
    
MODEL:
    ARCH: 'CLSFERBaseline'
    DEPTH: 2
    
TRAIN:
    EPOCHS: 1
    BASE_LR: 4e-4
    
    OPTIMIZER:
        NAME: 'Adam'
        EPS: 1e-7
        
    LR_SCHEDULER:
        NAME: 'None'
        
    CRITERION:
        NAME: 'CrossEntropy'
    