# RAF-DB_CLSFERNonMultiStage3.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 'CLSFERNonMultiStage3_LR'
    EXPERIMENT_PATH: '../autodl-tmp/results/FERPlus_CLSFERNonMultiStage3_LR'
    SAVE_FREQ: 30
    
DATA:
    BATCH_SIZE: 224
    DATASET: 'FERPlus'
    DATA_PATH: '../autodl-tmp/FERPlus'
    
MODEL:
    ARCH: 'NonMultiCLSFER_stage3'
    DEPTH: 8
    
    
TRAIN:
    EPOCHS: 60
    BASE_LR: 1e-5
    
    OPTIMIZER:
        NAME: 'Adam'
        EPS: 1e-8
        BETAS: (0.9, 0.999)
        
    LR_SCHEDULER:
        NAME: 'None'
        
    CRITERION:
        NAME: 'CrossEntropy'
    
    