# SFEW_AC_CAE_test.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 'SFEW_AC_CAE_test'
    EXPERIMENT_PATH: '../autodl-tmp/results/SFEW_AC-CAE'
    SAVE_FREQ: 100
    PRINT_FREQ: 30
    
DATA:
    IMG_SIZE: 112
    BATCH_SIZE: 32
    DATASET: 'SFEW'
    DATA_PATH: '../FERdatasets/SFEW'
    

MODEL:
    ARCH: '14x14_CLSFER_baseline'
    DEPTH: 8
    DROP_PATH: 0.5
    
    MLP_LAYER: 'linear'
    TOKEN_SE: 'conv2d'
    
    
TRAIN:
    EPOCHS: 5
    BASE_LR: 3.5e-5
    
    OPTIMIZER:
        NAME: 'esamAdam'
        EPS: 1e-8
        BETAS: (0.9, 0.999)
        RHO: 0.05
        
    LR_SCHEDULER:
        NAME: 'exponential'
        GAMMA: 0.98
        
    CRITERION:
        NAME: 'POSTERCrossEntropy'
        
AUG:
    MIXUP: 0.
    
    