# SingleStar_test.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 'single_star_tests'
    EXPERIMENT_PATH: './autodl-tmp/results/RAF-DB_single_star'
    SAVE_FREQ: 100
    PRINT_FREQ: 50
    
DATA:
    IMG_SIZE: 112
    BATCH_SIZE: 200
    DATASET: 'RAF-DB'
    DATA_PATH: '../FERdatasets/RAF-DB'
    ERASING_SCALE: (0.05, 0.05)
    ERASING_P: 0.5
    
MODEL:
    ARCH: 'starCAE-single'
    DEPTH: 8
    
    STARBLOCK:
        GATE: 'CAE'
        USE_STAR: True
        SHORTCUT: 'ljdfaoj'
    
TRAIN:
    EPOCHS: 50
    BASE_LR: 3.5e-5
    
    OPTIMIZER:
        NAME: 'esamAdam'
        EPS: 1e-8
        BETAS: (0.9, 0.999)
        RHO: 0.05
        
    LR_SCHEDULER:
        NAME: 'exponential'
        GAMMA: 0.98
        
    CRITERION:
        NAME: 'FocalLoss'
        
AUG:
    MIXUP: 0.
    
    