# test.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 'running_tests'
    EXPERIMENT_PATH: '../autodl-tmp/results/SingleStyle_multiCAE'
    SAVE_FREQ: 100
    PRINT_FREQ: 30
    
DATA:
    IMG_SIZE: 112
    BATCH_SIZE: 16
    VAL_BATCH_SIZE: 16
    DATASET: 'RAF-DB'
    DATA_PATH: '../FERdatasets/RAF-DB'
    
    
MODEL:
    ARCH: 'CrossStageAC-CAE'
    
    
TRAIN:
    EPOCHS: 20
    BASE_LR: 1e-4
    
    OPTIMIZER:
        NAME: 'Adam'
        EPS: 1e-8
        BETAS: (0.9, 0.999)
        RHO: 0.05
        
    LR_SCHEDULER:
        NAME: 'exponential'
        GAMMA: 0.98
        
    CRITERION:
        NAME: 'POSTERCrossEntropy'
        
AUG:
    MIXUP: 0.
    
    