# test.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 'CLSFER_Cross'
    EXPERIMENT_PATH: './results/RAF-DB_CLSFERCross'
    SAVE_FREQ: 100
    
DATA:
    IMG_SIZE: 112
    BATCH_SIZE: 128
    DATASET: 'RAF-DB'
    DATA_PATH: '../FERdatasets/RAF-DB'
    
MODEL:
    ARCH: 'cross_cls_CLSFER'
    DEPTH: 8
    
TRAIN:
    EPOCHS: 20
    BASE_LR: 1e-4
    
    OPTIMIZER:
        NAME: 'samAdam'
        EPS: 1e-8
        BETAS: (0.9, 0.999)
        
    LR_SCHEDULER:
        NAME: 'exponential'
        GAMMA: 0.98
        
    CRITERION:
        NAME: 'POSTERCrossEntropy'
        
AUG:
    MIXUP: 0.
    
    