# test.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 'running_tests'
    EXPERIMENT_PATH: './results/RAF-DB_CLSFERCross'
    SAVE_FREQ: 100
    PRINT_FREQ: 30
    
DATA:
    IMG_SIZE: 112
    BATCH_SIZE: 64
    DATASET: 'RAF-DB'
    DATA_PATH: '../FERdatasets/RAF-DB'
    
    
MODEL:
    ARCH: 'starCAE-single'
    DEPTH: 8
    DROP_PATH: 0.5
    
    STARBLOCK:
        GATE: 'CAE'
        USE_STAR: True
        SHORTCUT: 'skip'
    
TRAIN:
    EPOCHS: 5
    BASE_LR: 3.5e-5
    
    OPTIMIZER:
        NAME: 'esamAdam'
        EPS: 1e-8
        BETAS: (0.9, 0.999)
        
    LR_SCHEDULER:
        NAME: 'exponential'
        GAMMA: 0.98
        
    CRITERION:
        NAME: 'FocalLoss'
        
AUG:
    MIXUP: 0.
    
    