# test.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 'CLSFER_Cross'
    EXPERIMENT_PATH: './results/RAF-DB_CLSFERCross'
    SAVE_FREQ: 100
    PRINT_FREQ: 30
    
DATA:
    IMG_SIZE: 112
    BATCH_SIZE: 64
    DATASET: 'RAF-DB'
    DATA_PATH: '../FERdatasets/RAF-DB'
    
MODEL:
    ARCH: 'POSTER2'
    DEPTH: 8
    
TRAIN:
    EPOCHS: 5
    BASE_LR: 3.5e-5
    
    OPTIMIZER:
        NAME: 'samAdam'
        EPS: 1e-8
        BETAS: (0.9, 0.999)
        
    LR_SCHEDULER:
        NAME: 'exponential'
        GAMMA: 0.98
        
    CRITERION:
        NAME: 'FocalLoss'
        
AUG:
    MIXUP: 0.
    
    