# test.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 'CLSFERNonMulti_SearchDepth&LR'
    EXPERIMENT_PATH: './results/RAF-DB_CLSFERNonMulti_SearchDepth&LR_depth8_ep1e-8'
    SAVE_FREQ: 30
    
DATA:
    IMG_SIZE: 112
    BATCH_SIZE: 5
    DATASET: 'RAF-DB'
    DATA_PATH: '../FERdatasets/RAF-DB'
    
MODEL:
    ARCH: 'NonMultiCLSFER_addpatches'
    DEPTH: 8
    
TRAIN:
    EPOCHS: 3
    BASE_LR: 5e-5
    CONFUSION_MATRIX: True
    
    OPTIMIZER:
        NAME: 'samAdam'
        EPS: 1e-8
        BETAS: (0.9, 0.999)
        
    LR_SCHEDULER:
        NAME: 'exponential'
        GAMMA: 0.955
        
    CRITERION:
        NAME: 'CrossEntropy'
        
AUG:
    MIXUP: 1.0
    
    