# tSNE.yaml
SYSTEM:
    PROJECT_NAME: 'CLSFERBaseline'
    EXPERIMENT_NAME: 't-SNE'
    EXPERIMENT_PATH: '../autodl-tmp/results/FERPlus_CrossACCAE_tSNE'
    SAVE_FREQ: 100
    PRINT_FREQ: 50
    
DATA:
    IMG_SIZE: 112
    BATCH_SIZE: 32
    DATASET: 'FERPlus'
    DATA_PATH: '..\FERdatasets\FERPlus'
    
MODE:
    T_SNE: True
    
MODEL:
    ARCH: 'CrossACCAE_single'
    DEPTH: 12
    ATTN_DROP: 0.6
    
    MLP_LAYER: 'linear'
    
    
TRAIN:
    EPOCHS: 200
    BASE_LR: 3.5e-5
    RESUME: 'D:\College\projects\autodl-tmp\AC-CAE_best\FERplus\FERPlus_AC-CAE_Cross_[07-01]-[11-08]_89.38\checkpoint\best.pth'
    
    OPTIMIZER:
        NAME: 'samAdam'
        EPS: 1e-8
        BETAS: (0.9, 0.999)
        RHO: 0.05
        
    LR_SCHEDULER:
        NAME: 'exponential'
        GAMMA: 0.98
        
    CRITERION:
        NAME: 'POSTERCrossEntropy'
        
AUG:
    MIXUP: 0.
    
    